#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION=$(head ./configure.ac|grep AC_INIT|awk -F [ '{print $3}'|awk -F ] '{print $1}')

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/Xfce-Theme-Manager
find Xfce-Theme-Manager -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/Xfce-Theme-Manager/makepkg
rm -r /tmp/Xfce-Theme-Manager/DEVDATA
rm -r /tmp/Xfce-Theme-Manager/MakeTransList
mv /tmp/Xfce-Theme-Manager /tmp/Xfce-Theme-Manager-${VERSION}
tar -czvf Xfce-Theme-Manager-${VERSION}.tar.gz Xfce-Theme-Manager-${VERSION}
rm -r /tmp/Xfce-Theme-Manager-${VERSION}