#!/bin/bash -e

#©keithhedger Sun 4 Aug 12:15:59 BST 2013 kdhedger68713@gmail.com


LANGUAGE="POLISH"
INFILE=HELPTranslation.pl

cat $INFILE|grep $LANGUAGE|sed "s/$LANGUAGE://"|awk -F "\n" '{print "L\"" $1 "\""}'| tr "\n" ",">./outstring.help


INFILE=GUITranslation.pl

cat $INFILE|grep $LANGUAGE|sed "s/$LANGUAGE://"|awk -F "\n" '{print "\"" $1 "\""}'| tr "\n" ",">./outstring.gui
