#!/bin/bash -e

#©keithhedger Fri 2 Aug 12:20:31 BST 2013 kdhedger68713@gmail.com

THEMEARRAY=
ARRAYNUM=0

# C = just custom themes
# t = meta themes

THEMESORT=C

makeArray ()
{
	while read
		do
			THEMEARRAY[$ARRAYNUM]="$REPLY"
			((ARRAYNUM=ARRAYNUM+1))
		done< <(xfce-theme-manager -l $THEMESORT)
}


makeArray

THEMENUMBER=$RANDOM
MAXFILES=${#THEMEARRAY[@]}
THEMENUM=$(( (THEMENUMBER %=  MAXFILES-1) +1 ))
THEME=${THEMEARRAY[THEMENUM]}

xfce-theme-manager  -t "$THEME"
