#!/bin/bash

#©keithhedger Fri 2 Aug 12:20:09 BST 2013 kdhedger68713@gmail.com

# set random wallpaper

NUMMONITORS=2
BORDERSARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			BORDERSARRAY[$ARRAYNUM]="$REPLY"
			((ARRAYNUM=ARRAYNUM+1))
		done< <(xfce-theme-manager -l b)
}


makeArray

for((j=0;j<NUMMONITORS;j++))
	do
		WALLNUMBER=$RANDOM
		MAXFILES=${#BORDERSARRAY[@]}
		PICNUM=$(( (WALLNUMBER %=  MAXFILES-1) +1 ))
		PIC=${BORDERSARRAY[PICNUM]}

#set monitor to j
#set wallpaperstyle to auto
		xfce-theme-manager -e 0 -m $j -b "$PIC"
done