#!/bin/bash

#©keithhedger Fri 2 Aug 12:20:31 BST 2013 kdhedger68713@gmail.com

THEMEARRAY=
ARRAYNUM=0
#THEMEPARTS=C just custom themes
#THEMEPARTS=C just meta themes
#THEMEPARTS=Ct both

THEMEPARTS=C
makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				THEMEARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l $THEMEPARTS)
}


makeArray

if [ -e ~/.config/XfceThemeManager/themenumber ];then
	THEMENUM=$(cat ~/.config/XfceThemeManager/themenumber)
	if [ $THEMENUM -ge ${#THEMEARRAY[@]} ];then
		THEMENUM=0
	fi
else
	THEMENUM=0
fi

xfce-theme-manager  -t "${THEMEARRAY[THEMENUM]}"
((THEMENUM++))
echo -n $THEMENUM > ~/.config/XfceThemeManager/themenumber
