#!/bin/bash

#©keithhedger Fri 2 Aug 12:20:09 BST 2013 kdhedger68713@gmail.com

MONITORNUMBER=0
BORDERSARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				BORDERSARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l b|sort)
}


makeArray

if [ -e ~/.config/XfceThemeManager/wallpapernumber ];then
	PAPERNUM=$(cat ~/.config/XfceThemeManager/wallpapernumber)
else
	PAPERNUM=0
fi

((PAPERNUM++))

xfce-theme-manager -e 0 -m $MONITORNUMBER -b "${BORDERSARRAY[PAPERNUM]}"

echo $PAPERNUM > ~/.config/XfceThemeManager/wallpapernumber