#!/bin/bash

#©keithhedger Fri 2 Aug 12:21:33 BST 2013 kdhedger68713@gmail.com

GTKARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				GTKARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l c)
}


makeArray

if [ -e ~/.config/XfceThemeManager/gtknumber ];then
	GTKNUM=$(cat ~/.config/XfceThemeManager/gtknumber)
	if [ $GTKNUM -ge ${#GTKARRAY[@]} ];then
		GTKNUM=0
	fi
else
	GTKNUM=0
fi

xfce-theme-manager  -c "${GTKARRAY[GTKNUM]}"
((GTKNUM++))
echo -n $GTKNUM > ~/.config/XfceThemeManager/gtknumber
