#!/bin/bash

#©keithhedger Fri 2 Aug 12:21:33 BST 2013 kdhedger68713@gmail.com

WMBARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				WMBARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l w)
}


makeArray

if [ -e ~/.config/XfceThemeManager/wmbnumber ];then
	PAPERNUM=$(cat ~/.config/XfceThemeManager/wmbnumber)
	if [ $PAPERNUM -gt ${#WMBARRAY[@]} ];then
		PAPERNUM=0
	fi
else
	PAPERNUM=0
fi

xfce-theme-manager  -w "${WMBARRAY[PAPERNUM]}"
((PAPERNUM++))
echo -n $PAPERNUM > ~/.config/XfceThemeManager/wmbnumber
