#!/bin/bash

#©keithhedger Fri 2 Aug 12:21:33 BST 2013 kdhedger68713@gmail.com

WMBARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				WMBARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l w)
}


makeArray

if [ -e ~/.config/XfceThemeManager/wmbnumber ];then
	WMBNUM=$(cat ~/.config/XfceThemeManager/wmbnumber)
	if [ $WMBNUM -ge ${#WMBARRAY[@]} ];then
		WMBNUM=0
	fi
else
	WMBNUM=0
fi

xfce-theme-manager  -w "${WMBARRAY[WMBNUM]}"
((WMBNUM++))
echo -n $WMBNUM > ~/.config/XfceThemeManager/wmbnumber
