#!/bin/bash

#©keithhedger Fri 2 Aug 12:21:33 BST 2013 kdhedger68713@gmail.com

GTKARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				GTKARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l c)
}


makeArray

if [ -e ~/.config/XfceThemeManager/gtknumber ];then
	PAPERNUM=$(cat ~/.config/XfceThemeManager/gtknumber)
	if [ $PAPERNUM -gt ${#GTKARRAY[@]} ];then
		PAPERNUM=0
	fi
else
	PAPERNUM=0
fi

xfce-theme-manager  -c "${GTKARRAY[PAPERNUM]}"
((PAPERNUM++))
echo -n $PAPERNUM > ~/.config/XfceThemeManager/gtknumber
