#!/bin/bash

#©keithhedger Fri 2 Aug 12:20:09 BST 2013 kdhedger68713@gmail.com

MONITORNUMBER=0
PAPERSARRAY=
ARRAYNUM=0

makeArray ()
{
	while read
		do
			if [ ${REPLY:0:1} != "[" ];then
				PAPERSARRAY[$ARRAYNUM]="$REPLY"
				((ARRAYNUM=ARRAYNUM+1))
			fi
		done< <(xfce-theme-manager -l b|sort)
}


makeArray

if [ -e ~/.config/XfceThemeManager/wallpapernumber ];then
	PAPERNUM=$(cat ~/.config/XfceThemeManager/wallpapernumber)
	if [ $PAPERNUM -ge ${#PAPERSARRAY[@]} ];then
		PAPERNUM=0
	fi
else
	PAPERNUM=0
fi

xfce-theme-manager -e 0 -m $MONITORNUMBER -b "${PAPERSARRAY[PAPERNUM]}"

((PAPERNUM++))
echo -n $PAPERNUM > ~/.config/XfceThemeManager/wallpapernumber