#!/bin/bash -e

ENGLISH="Themes;Window Borders;Controls;Icons;Cursors;Wallpapers;Re-Build The Database;Rebuild DB;Launch Xfce-Composite-Editor;Backdrop Adjustments;Brightness;Saturation;Reset;Button Layout;Font Selection;WM Font;App Font;Cursor Size;Reset Theme;Save Theme;Advanced;Title Position;"

SPANISH="Temas;Bordes De Ventana;Controles;Iconos;Cursores;Fondos De Pantalla;Re-Crear La Base De Datos;Reconstruir DB;Lanzamiento Xfce-Composite-Editor;Ajustes De Telón De Fondo;Brillo;Saturación;Reajustar;Diseño De Los Botones;Selección De Fuentes;WM Fuente;Aplicación De Fuentes;Tamaño Del Cursor;Restablecer Tema;Guardar Tema;Avanzado;Título Del Puesto"
