#!/bin/bash -e

cd $(dirname "$0")

ENGLISH="Themes;Window Borders;Controls;Icons;Cursors;Wallpapers;Re-Build The Database;Rebuild DB;Launch Xfce-Composite-Editor;Backdrop Adjustments;Brightness;Saturation;Reset;Button Layout;Font Selection;WM Font;App Font;Cursor Size;Reset Theme;Save Theme;Advanced;Title Position;END"

SPANISH="Temas;Bordes De Ventana;Controles;Iconos;Cursores;Fondos De Pantalla;Re-Crear La Base De Datos;Reconstruir DB;Lanzamiento Xfce-Composite-Editor;Ajustes De Telón De Fondo;Brillo;Saturación;Reajustar;Diseño De Los Botones;Selección De Fuentes;WM Fuente;Aplicación De Fuentes;Tamaño Del Cursor;Restablecer Tema;Guardar Tema;Avanzado;Título Del Puesto;"


language=$(echo ${LANG:0:2})

case $language in

	"es")
		while read
			do
				fromstr="$ENGLISH"
				tostr="$SPANISH"
				while [ "$fromstr" != "END" ]
					do
						fromword="${fromstr%%;?*}"
						fromstr="${fromstr#?*;}"
						toword="${tostr%%;?*}"
						tostr="${tostr#?*;}"
						#echo $REPLY "---"${fromword}"==="${toword}"+++"
						sed -i "s/$fromword/$toword/g" "$REPLY"
					done
					
			done < <(find "./" -maxdepth 1 -mindepth 1)
		echo spanish
		;;
	*)
		echo "Sorry no translation for your language ...:("
		echo "Please think about submitting a translation"
		;;
esac


